version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wind_reseller_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wind_reseller
      POSTGRES_USER: winduser
      POSTGRES_PASSWORD: 2H8z0MhL7tZpk6p6
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - wind_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "winduser", "-d", "wind_reseller"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
    container_name: wind_reseller_bot
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URI: postgresql://winduser:2H8z0MhL7tZpk6p6@db:5432/wind_reseller
    volumes:
      - ./:/app
    networks:
      - wind_network

networks:
  wind_network:
    driver: bridge

volumes:
  postgres_data:
